/* eslint-disable react/jsx-key */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import Card from '../components/card'

import styles from '../styles/Home.module.css'

import coffeeStoresData from "../data/coffee-stores.json";

/** All code here is server side rendering, then this code only appear in server, 
    client ill not see any code here */
export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

/** Otherwise code here ill appear in client side because this is client side code */
export default function Home(props) {
  console.log("props", props);

  const handleOnBannerBtnClick = () =>{
    console.log("Hi hello!");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />

        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={500} height={375}/>
        </div>

        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>

            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card 
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/coffee-store/${coffeeStore.id}`}
                  />    
                );
              })}
            </div>
          </>
        )}  
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
